### PR TITLE
Fixed "Fat finger" message + small code clean up

### PR DESCRIPTION
**Pull request by albertopoljak**
Message no longer shows up twice.
Code clean up: While resolving the issue I came across several mistakes and unnecessary variables:
playAgainPrompt()==true is unnecessary because that function itself returns boolean,
Also cleaned function playAgainPrompt because it used unnecessary variables.

### CODE REVIEW

**Comment by albertopoljak** [comment]
Since function playAgainPrompt() is completely changed it won't accept automatic merge :/

**Comment by SirXOPHER** [comment]
@albertopoljak , you are on fire! Looks great and I am happy to accept those changes. Now that we have the "minimal viable product" running, we can focus on clean code, more features and enhancements. Thanks for the fix and clean up, makes all sense as far as I can see.

The pull request dialog once more doesn't offer an automatic merge. You suspected it is because of the major rework you've been doing, but it could also be that you've missed my minor cleanup iteration of the source code that I pushed to the master only minutes after the merge with your previous resolution. I mainly removed comments regarding the resolved issue and inserted new comments to highlight the new issue. How can we avoid working on different code bases?

I will look into resolving the conflicts (don't know how exactly to achieve that yet) or perhaps revert my minor cleanup iteration and then it may allow the automatic merge?

**Comment by SirXOPHER** [comment]
Okay, I think I resolved the existing conflicts. Let's hope I didn't break anything. It was a good learning experience, though.

**Comment by albertopoljak** [comment]
Yup it works so no broken code yet.

**Pull request merged**
